name: Assign Project to New Issues

on:
  issues:
    types: [opened]

jobs:
  assign_project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Assign issue to project
      uses: octokit/request-action@v2
      with:
        route: POST /projects/columns/cards
        project_id: 1
        content_id: ${{ github.event.issue.id }}
        content_type: Issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
